apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthy-app
spec:
  selector:
    matchLabels:
      app: healthy-app
  template:
    metadata:
      labels:
        app: healthy-app
    spec:
      containers:
        - name: main
          image: nginx
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: healthy-app-service
spec:
  selector:
    app: healthy-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
